op_strings = {
    'Add': '**Increment**',
    'Sub': '**Decrement**',
    'In': 'contains',
    'NotIn': 'does not contain',
    'Eq': 'is equal',
    'NotEq': 'is equal',
    'Lt': 'is less than',
    'LtE': 'is less than or equal to',
    'Gt': '$is greater than$',
    'GtE': '$is greater than or equal to$',
}

symbols = {
    'Add': '+',
    'Mult': '*',
    'FloorDiv': '//',
    'Div': '/',
    'Pow': '^',
    'Sub': '-',
    'Mod': '%',
    'Eq': '=',
    'NotEq': '!=',
    'Lt': '<',
    'LtE': '<=',
    'Gt': '>',
    'GtE': '>=',
    'LShift': '<<',
    'RShift': '>>',
}
